sonar.projectKey=ecommerce-frontend
sonar.projectName=ecommerce-frontend
sonar.projectVersion=1.0

#sonar.sources=js,fonts,css
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,**/*.woff,**/*.woff2,**/*.eot,**/*.ttf,**/*.otf
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# JavaScript configuration
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

sonar.host.url=http://localhost:9000
sonar.token=squ_134e7abf8371ef8ff8790e21c78ad0bddb232a21
