# SonarQube server (localhost - for SonarCloud use https://sonarcloud.io + sonar.organization)
sonar.host.url=http://localhost:9000
sonar.token=sqp_ab515c4543afe96fc6f9b7ba2d88fd9cf560aabd

# Project identification
sonar.projectKey=E-Commerce
sonar.projectName=E-Commerce
