# Clé = exactement celle affichée dans SonarQube (sensible à la casse). Ex. liste API : E-Commerce, com.ecommerce:ecommerce-backend — pas "Ecommerce".
sonar.host.url=http://localhost:9000
sonar.token=squ_134e7abf8371ef8ff8790e21c78ad0bddb232a21
sonar.projectKey=com.ecommerce:ecommerce-backend
sonar.projectName=Ecommerce
